import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar/Navbar";
import { Search } from "./components/NavBar/Search";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Val DB",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <NavBar /> 
         
        </div>
        {children}
      </body>
    </html>
  );
}
