import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "../components/NavBar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Val DB",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>
        <div className="relative min-h-screen">
          <NavBar />
          <div>{children}</div>
        </div>
      </body>
    </html>
  );
}
